import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker,{b64,unb64} from '../src/worker.mjs';
class D1 {
 constructor(){this.db=new DatabaseSync(':memory:');this.db.exec(readFileSync(new URL('../migrations/0001.sql',import.meta.url),'utf8'));}
 prepare(sql){const self=this;let args=[];return {bind(...a){args=a;return this;},async first(){return self.db.prepare(sql).get(...args)||null;},async run(){const s=self.db.prepare(sql);if(/RETURNING/i.test(sql)||/^SELECT/.test(sql))return {results:s.all(...args),meta:{changes:0}};const r=s.run(...args);return {results:[],meta:{changes:Number(r.changes)}};}};}
 async batch(stmts){this.db.exec('BEGIN');try{const r=[];for(const s of stmts)r.push(await s.run());this.db.exec('COMMIT');return r;}catch(e){this.db.exec('ROLLBACK');throw e;}}
}
async function setup(){const pair=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);return {DB:new D1(),SIGNING_PRIVATE_JWK:JSON.stringify(await crypto.subtle.exportKey('jwk',pair.privateKey)),ADMIN_TOKEN:'admin-test',ISSUANCE_SECRET:'test-only',SIGNING_KEY_ID:'resone-1',LEASE_SECONDS:'604800',INSTRUCTION_KEY_BASE64:Buffer.alloc(32,7).toString('base64')};}
async function call(env,path,b,admin=false){const r=await worker.fetch(new Request('https://licenses.test'+path,{method:'POST',headers:admin?{Authorization:'Bearer '+env.ADMIN_TOKEN}:{},body:JSON.stringify(b)}),env);return {status:r.status,...await r.json()};}
async function device(){const p=await crypto.subtle.generateKey({name:'ECDSA',namedCurve:'P-256'},true,['sign','verify']);return {privateKey:p.privateKey,publicKey:await crypto.subtle.exportKey('jwk',p.publicKey)};}
async function proof(env,d,key,action){const {challenge}=await call(env,'/v1/challenge',{action,licenseKey:key,devicePublicKey:d.publicKey});return {challenge,licenseKey:key,devicePublicKey:d.publicKey,signature:b64(await crypto.subtle.sign({name:'ECDSA',hash:'SHA-256'},d.privateKey,new TextEncoder().encode(challenge)))};}
async function issue(env){return call(env,'/admin/issue',{provider:'itch',purchaseId:'purchase-1'},true);}

test('domain verification file returns exact plain-text token',async()=>{
 const r=await worker.fetch(new Request('https://licenses.test/.well-known/pki-validation/01a0bc28-2ec7-7db3-abe1-a20b8f279de8.txt'),{});
 assert.equal(r.status,200);
 assert.match(r.headers.get('content-type')||'',/^text\/plain\b/i);
 assert.equal(await r.text(),'B8FxYSQms8N98euAXGKJ8YUuY8Y');
});
test('purchase authorization, idempotency, and no purchase-ID activation',async()=>{const e=await setup();assert.equal((await call(e,'/admin/issue',{provider:'itch',purchaseId:'purchase-1'})).status,401);const a=await issue(e),b=await issue(e);assert.equal(a.licenseKey,b.licenseKey);assert.equal(a.licenseId,b.licenseId);const d=await device();assert.equal((await call(e,'/v1/activate',await proof(e,d,'purchase-1','activate'))).status,409);});
test('signed activation, replay rejection, second device rejection, renew and tamper',async()=>{const e=await setup(),a=await issue(e),d=await device(),other=await device();const p=await proof(e,d,a.licenseKey,'activate');const r=await call(e,'/v1/activate',p);assert.equal(r.status,200);const [h,c,s]=r.lease.split('.');const pub=JSON.parse(e.SIGNING_PRIVATE_JWK);delete pub.d;delete pub.key_ops;assert(await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},await crypto.subtle.importKey('jwk',pub,{name:'ECDSA',namedCurve:'P-256'},false,['verify']),unb64(s),new TextEncoder().encode(h+'.'+c)));assert.equal((await call(e,'/v1/activate',p)).status,409);assert.equal((await call(e,'/v1/activate',await proof(e,other,a.licenseKey,'activate'))).status,409);assert.equal((await call(e,'/v1/renew',await proof(e,d,a.licenseKey,'renew'))).status,200);const bad=await proof(e,d,a.licenseKey,'renew');bad.signature=b64(new Uint8Array(64));assert.equal((await call(e,'/v1/renew',bad)).status,401);});
test('release preserves outstanding lease, later transfer, revoke blocks renewal',async()=>{const e=await setup(),a=await issue(e),d=await device(),other=await device();await call(e,'/v1/activate',await proof(e,d,a.licenseKey,'activate'));assert.equal((await call(e,'/v1/release',await proof(e,d,a.licenseKey,'release'))).status,200);assert.equal((await call(e,'/v1/renew',await proof(e,d,a.licenseKey,'renew'))).status,409);assert.equal((await call(e,'/v1/activate',await proof(e,other,a.licenseKey,'activate'))).status,409);e.DB.db.exec('UPDATE licenses SET lease_until=0');assert.equal((await call(e,'/v1/activate',await proof(e,other,a.licenseKey,'activate'))).status,200);await call(e,'/admin/revoke',{provider:'itch',purchaseId:'purchase-1'},true);assert.equal((await call(e,'/v1/renew',await proof(e,other,a.licenseKey,'renew'))).status,409);});
test('challenge cannot be used for another action or another device',async()=>{const e=await setup(),a=await issue(e),d=await device(),o=await device();const p=await proof(e,d,a.licenseKey,'activate');assert.equal((await call(e,'/v1/renew',p)).status,401);p.devicePublicKey=o.publicKey;assert.equal((await call(e,'/v1/activate',p)).status,401);});
test('expired challenge and oversized actual body rejected',async()=>{const e=await setup();const {sign}=await import('../src/worker.mjs');const token=await sign(e,{iss:'resone-licensing',exp:0,iat:0});assert.equal((await call(e,'/v1/activate',{challenge:token})).status,401);assert.equal((await call(e,'/v1/challenge',{large:'x'.repeat(20000)})).status,413);});

test('instruction key is delivered only to the activated device with a live lease',async()=>{const e=await setup(),a=await issue(e),d=await device(),other=await device();await call(e,'/v1/activate',await proof(e,d,a.licenseKey,'activate'));const key=await call(e,'/v1/instruction-key',await proof(e,d,a.licenseKey,'instruction-key'));assert.equal(key.status,200);assert.equal(Buffer.from(key.instructionKey,'base64').length,32);assert.equal((await call(e,'/v1/instruction-key',await proof(e,other,a.licenseKey,'instruction-key'))).status,409);e.DB.db.exec('UPDATE licenses SET lease_until=0');assert.equal((await call(e,'/v1/instruction-key',await proof(e,d,a.licenseKey,'instruction-key'))).status,409);});
